url: https://minnehack.github.io
baseurl: 

# Site settings
title: MinneHack
email: acm@cs.umn.edu
description: "ACM presents MinneHack 2015, a 24 Hour Hackathon competition hosted at the University of Minnesota"

# Color settings (hex-codes without the leading hash-tag)
# color:
#   primary: fed136
#   secondary: fec503  
#   secondary-dark: 333

color:
  primary: fed136
  secondary: fec503
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Flying Walrus
  pic: carleton
  position: Carleton College
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Hack To the Future
  pic: umn
  position: University of Minnesota
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Beta Eagles
  pic: augsburg 
  position: Augsburg College
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/acmuofmn
  - title: facebook
    url: https://www.facebook.com/acmuofmn

# Postal address (add as many lines as necessary)
address:
  - line: 200 Union Street SE
  - line: Minneapolis, MN 55455

# Build settings
markdown: kramdown
permalink: pretty
